 -- 테이블 삭제(DATE 삭제와 구분 해야함)
 -- DELETE는 ROLLBACK, COMMIT 가능. DROP는 ROLLBACK, COMMIT 불가능. 
 DROP TABLE basic_board; -- TABLE 삭제
 -- DELETE FROM basic_board; DATE 삭제
 
 -- 게시판 프로그램 테이블 생성
 CREATE TABLE BASIC_BOARD(
	-- 컬럼명 데이터타입 [제약조건들]
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, TITLE VARCHAR(50) NOT NULL
	, WRITER VARCHAR(50) NOT NULL
	, CONTENT VARCHAR(100)
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, READ_CNT INT DEFAULT 0
 );
 
INSERT INTO basic_board (TITLE, WRITER, CONTENT)
VALUES ('BYE', 'SON', 'GOOD');
 
INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER)
VALUES (2, 'HI', 'PACK');
 
 SELECT * FROM basic_board;
 
INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT) 
VALUES(1, '제목', '작성자', '내용', '2024-07-01', 1); 
 
INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE) 
VALUES(2, '제목', '작성자1', '내용1', '2024-07-01');

INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT) 
VALUES(3, '제목', '작성자2', '내용', '2024-07-01' , 3);

SLECT BOARD_NUM
	, TITLE
	, WRITER
	, CREATE_DATE
	, READ_CNT
FROM basic_board
WHERE #{searchKeyword} LIKE '%안녕%';
WHERE #{searchValue} LIKE '%java%';