CREATE TABLE CAR_INFO (
	MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY 
	, MODEL_NAME VARCHAR(30) NOT NULL
	, MODEL_PRICE VARCHAR(10) NOT NULL
	, MODEL_BRAND VARCHAR(10) NOT NULL
);

SELECT * FROM CAR_INFO;

CREATE TABLE SALES_INFO (
	SALES_NUM INT  AUTO_INCREMENT PRIMARY KEY
	, BUYER_NAME VARCHAR(5) NOT NULL
	, BUYER_TEL VARCHAR(11)
	, SALES_COLOR VARCHAR(20) NOT NULL
	, SALES_DATA VARCHAR(20) NOT NULL
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM)
);

SELECT * FROM SALES_INFO;