-- react 기본 게시판 프로젝트
CREATE TABLE REACT_BOARD (
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(100)
	, BOARD_WRITER VARCHAR(30) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO REACT_BOARD (
	BOARD_TITLE
	, BOARD_CONTENT
	, BOARD_WRITERbasic_boarddeptbasic_board
) VALUES (
	'첫번째 게시글'
	, '내용입니다'
	, '김자바'
);

SELECT * FROM react_bostudy_dbard;

CREATE TABLE REACT_STUDENT (
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(30) NOT NULL
	, KOR_SCORE INT
	, ENG_SCORE INT
	, MATH_SCORE INT
	, STU_AGE INT
	, STU_TEL VARCHAR(20) UNIQUE -- 010-1111-2222
	, STU_ADDR VARCHAR(50)
);

SELECT * FROM REACT_STUDENT;
