CREATE TABLE SCORE_INFO (
	STU_NUM INT PRIMARY KEY
	, STU_NAME VARCHAR(50)
	, KOR_SCORE INT
	, ENG_SCORE INT
	, INTRO VARCHAR(100)
);

INSERT INTO SCORE_INFO
VALUES (1, '홍길동', 80, 90 , '반가워요');

INSERT INTO SCORE_INFO
VALUES (2, '이길동', 70, 80, '안녕');

INSERT INTO SCORE_INFO
VALUES (3, '김길동', 60, 70, '안녕하세요');

INSERT INTO SCORE_INFO
VALUES (4, '박길동', 75, 85, '안녕못해요');

INSERT INTO SCORE_INFO
VALUES (5, '장길동', 50, 60, '반갑다');

SELECT * FROM score_info;
